[build]
  publish = "public"
  command = "python main.py"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/feed.xml"
  to = "/output/feed.xml"
  status = 200

[[redirects]]
  from = "/feed.atom"
  to = "/output/feed.atom"
  status = 200

[[redirects]]
  from = "/feed.json"
  to = "/output/feed.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/feed.*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"